// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using swsec_intro_backend_dotnet.Data;

#nullable disable

namespace swsec_intro_backend_dotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241030010554_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("swsec_intro_backend_dotnet.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "fio",
                            Type = 2,
                            Username = "zorzal"
                        },
                        new
                        {
                            Id = 2,
                            Password = "123",
                            Type = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 3,
                            Password = "fiofio",
                            Type = 2,
                            Username = "chincol"
                        },
                        new
                        {
                            Id = 4,
                            Password = "pah",
                            Type = 2,
                            Username = "tiuque"
                        },
                        new
                        {
                            Id = 5,
                            Password = "roji",
                            Type = 2,
                            Username = "loica"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
